source c:\pam\mysql\scripts\create_pam_schema\DATABASE_pamdemo.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_FAMILY_pamdemo_actions.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_FAMILY_pamdemo_actual_config.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_FAMILY_pamdemo_agent_groups.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_FAMILY_pamdemo_agent_rules.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_FAMILY_pamdemo_agent_tree.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_FAMILY_pamdemo_agents.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_FAMILY_pamdemo_categories.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_FAMILY_pamdemo_categorytype_labels.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_FAMILY_pamdemo_change_requests.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_FAMILY_pamdemo_change_targets.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_FAMILY_pamdemo_changes.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_FAMILY_pamdemo_comments.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_FAMILY_pamdemo_goodagents.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_FAMILY_pamdemo_loaded_kms.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_FAMILY_pamdemo_name_changes.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_FAMILY_pamdemo_names.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_FAMILY_pamdemo_ooc.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_FAMILY_pamdemo_parameter_categories.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_FAMILY_pamdemo_parameter_descriptions.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_FAMILY_pamdemo_people.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_FAMILY_pamdemo_people_groups.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_FAMILY_pamdemo_purgelist.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_FAMILY_pamdemo_request_rules.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_FAMILY_pamdemo_rights.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_FAMILY_pamdemo_rules.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_FAMILY_pamdemo_ruleset_groups.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_FAMILY_pamdemo_rulesets.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_FAMILY_pamdemo_scheduled_changes.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_FAMILY_pamdemo_server_groups.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_FAMILY_pamdemo_thresholds.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_FAMILY_pamdemo_user_groups.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_FAMILY_pamdemo_integration_tables.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_CONTENTS_pamdemo_actions.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_CONTENTS_pamdemo_actual_config.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_CONTENTS_pamdemo_agent_groups.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_CONTENTS_pamdemo_agent_rules.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_CONTENTS_pamdemo_agent_tree.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_CONTENTS_pamdemo_agents.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_CONTENTS_pamdemo_categories.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_CONTENTS_pamdemo_change_requests.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_CONTENTS_pamdemo_change_targets.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_CONTENTS_pamdemo_changes.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_CONTENTS_pamdemo_comments.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_CONTENTS_pamdemo_goodagents.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_CONTENTS_pamdemo_loaded_kms.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_CONTENTS_pamdemo_name_changes.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_CONTENTS_pamdemo_names.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_CONTENTS_pamdemo_ooc.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_CONTENTS_pamdemo_parameter_categories.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_CONTENTS_pamdemo_parameter_descriptions.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_CONTENTS_pamdemo_people.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_CONTENTS_pamdemo_people_groups.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_CONTENTS_pamdemo_purgelist.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_CONTENTS_pamdemo_request_rules.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_CONTENTS_pamdemo_rights.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_CONTENTS_pamdemo_rules.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_CONTENTS_pamdemo_ruleset_groups.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_CONTENTS_pamdemo_rulesets.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_CONTENTS_pamdemo_scheduled_changes.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_CONTENTS_pamdemo_server_groups.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_CONTENTS_pamdemo_thresholds.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_CONTENTS_pamdemo_user_groups.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_REFERENCES_pamdemo_actions.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_REFERENCES_pamdemo_actual_config.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_REFERENCES_pamdemo_agent_groups.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_REFERENCES_pamdemo_agent_rules.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_REFERENCES_pamdemo_agent_tree.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_REFERENCES_pamdemo_agents.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_REFERENCES_pamdemo_categories.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_REFERENCES_pamdemo_change_requests.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_REFERENCES_pamdemo_change_targets.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_REFERENCES_pamdemo_changes.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_REFERENCES_pamdemo_comments.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_REFERENCES_pamdemo_goodagents.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_REFERENCES_pamdemo_loaded_kms.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_REFERENCES_pamdemo_name_changes.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_REFERENCES_pamdemo_names.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_REFERENCES_pamdemo_ooc.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_REFERENCES_pamdemo_parameter_categories.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_REFERENCES_pamdemo_parameter_descriptions.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_REFERENCES_pamdemo_people.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_REFERENCES_pamdemo_people_groups.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_REFERENCES_pamdemo_purgelist.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_REFERENCES_pamdemo_request_rules.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_REFERENCES_pamdemo_rights.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_REFERENCES_pamdemo_rules.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_REFERENCES_pamdemo_ruleset_groups.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_REFERENCES_pamdemo_rulesets.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_REFERENCES_pamdemo_scheduled_changes.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_REFERENCES_pamdemo_server_groups.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_REFERENCES_pamdemo_thresholds.sql
source c:\pam\mysql\scripts\create_pam_schema\TABLE_REFERENCES_pamdemo_user_groups.sql
