CREATE TABLE pamdemo.agent_table (
    `HOST_DISPLAY` VARCHAR ( 50 ) DEFAULT NULL,
    `PORT_NUMBER` INT ( 6 ) DEFAULT NULL,
    `PARENTS` text,
    `HOSTNAME` VARCHAR ( 30 ) DEFAULT NULL,
    `PROTOCOL` CHAR ( 3 ) DEFAULT NULL,
    `DATE_ENTERED` datetime DEFAULT NULL
) ENGINE = MyISAM DEFAULT CHARSET = latin1;

CREATE TABLE pamdemo.config_table (
    `HOSTNAME` VARCHAR ( 30 ) DEFAULT NULL,
    `PORT_NUMBER` INT ( 6 ) DEFAULT NULL,
    `DATE_SENT` datetime DEFAULT NULL,
    `DATE_ENTERED` datetime DEFAULT NULL,
    `CONFIG_VARIABLE` VARCHAR ( 200 ) DEFAULT NULL,
    `CONFIG_VALUE` text
) ENGINE = MyISAM DEFAULT CHARSET = latin1;

CREATE TABLE pamdemo.group_table (
    `GROUP_NAME` VARCHAR ( 200 ) DEFAULT NULL,
    `PARENT` text,
    `RULESET_TO_APPLY` text,
    `POSITION` INT ( 4 ) DEFAULT NULL,
    `DATE_ENTERED` datetime DEFAULT NULL
) ENGINE = MyISAM DEFAULT CHARSET = latin1;

CREATE TABLE pamdemo.km_version_table (
    `HOSTNAME` VARCHAR ( 30 ) DEFAULT NULL,
    `PORT_NUMBER` INT ( 6 ) DEFAULT NULL,
    `DATE_SENT` datetime DEFAULT NULL,
    `DATE_ENTERED` datetime DEFAULT NULL,
    `KM_NAME` VARCHAR ( 30 ) DEFAULT NULL,
    `KM_VERSION` VARCHAR ( 7 ) DEFAULT NULL,
    `KM_STATIC` CHAR ( 3 ) DEFAULT NULL,
    `KM_CONSOLE` INT ( 4 ) DEFAULT NULL
) ENGINE = MyISAM DEFAULT CHARSET = latin1;

CREATE TABLE pamdemo.rulesets_table (
    `RULESETNAME` text,
    `PARENT` text,
    `DATE_ENTERED` datetime DEFAULT NULL,
    `CONFIG_VARIABLE` VARCHAR ( 200 ) DEFAULT NULL,
    `PCONFIG_ACTION` VARCHAR ( 10 ) DEFAULT NULL,
    `CONFIG_VALUE` text
) ENGINE = MyISAM DEFAULT CHARSET = latin1;

CREATE TABLE pamdemo.threshold_table (
    `DATE_SENT` datetime DEFAULT NULL,
    `DATE_ENTERED` datetime DEFAULT NULL,
    `HOSTNAME` VARCHAR ( 30 ) DEFAULT NULL,
    `IP_ADDRESS` VARCHAR ( 20 ) DEFAULT NULL,
    `PORT_NUMBER` INT ( 6 ) DEFAULT NULL,
    `PORT_NUMBER_UDP` INT ( 6 ) DEFAULT NULL,
    `APP_CLASS` VARCHAR ( 50 ) DEFAULT NULL,
    `INSTANCE` VARCHAR ( 200 ) DEFAULT NULL,
    `PARAMETER` VARCHAR ( 50 ) DEFAULT NULL,
    `BORDER_ACTIVE` INT ( 1 ) DEFAULT NULL,
    `BORDER_MIN` INT ( 8 ) DEFAULT NULL,
    `BORDER_MAX` INT ( 8 ) DEFAULT NULL,
    `BORDER_TRIGGER` INT ( 1 ) DEFAULT NULL,
    `BORDER_OCCUR` INT ( 3 ) DEFAULT NULL,
    `BORDER_STATE` INT ( 1 ) DEFAULT NULL,
    `BORDER_RECOV` INT ( 1 ) DEFAULT NULL,
    `ALARM1_ACTIVE` INT ( 1 ) DEFAULT NULL,
    `ALARM1_MIN` INT ( 8 ) DEFAULT NULL,
    `ALARM1_MAX` INT ( 8 ) DEFAULT NULL,
    `ALARM1_TRIGGER` INT ( 1 ) DEFAULT NULL,
    `ALARM1_OCCUR` INT ( 3 ) DEFAULT NULL,
    `ALARM1_STATE` INT ( 1 ) DEFAULT NULL,
    `ALARM1_RECOV` INT ( 1 ) DEFAULT NULL,
    `ALARM2_ACTIVE` INT ( 1 ) DEFAULT NULL,
    `ALARM2_MIN` INT ( 8 ) DEFAULT NULL,
    `ALARM2_MAX` INT ( 8 ) DEFAULT NULL,
    `ALARM2_TRIGGER` INT ( 1 ) DEFAULT NULL,
    `ALARM2_OCCUR` INT ( 3 ) DEFAULT NULL,
    `ALARM2_STATE` INT ( 1 ) DEFAULT NULL,
    `ALARM2_RECOV` INT ( 1 ) DEFAULT NULL,
    `POLLTIME` INT ( 6 ) DEFAULT NULL,
    `KM_LOCALIZED` VARCHAR ( 6 ) DEFAULT NULL,
    `PARAM_VALUE` INT ( 8 ) DEFAULT NULL,
    `PARAM_TYPE` VARCHAR ( 5 ) DEFAULT NULL,
    `ARSALARM` INT ( 1 ) DEFAULT NULL,
    `ARSWARN` INT ( 1 ) DEFAULT NULL,
    `ARSINFO` INT ( 1 ) DEFAULT NULL,
    `MSGTXTALARM` VARCHAR ( 200 ) DEFAULT NULL,
    `MSGTXTWARN` VARCHAR ( 200 ) DEFAULT NULL,
    `MSGTXTINFO` VARCHAR ( 200 ) DEFAULT NULL,
    `ALERTSYTEM` VARCHAR ( 6 ) DEFAULT NULL,
    `CUSTOMID1` VARCHAR ( 100 ) DEFAULT NULL,
    `CUSTOMID2` VARCHAR ( 100 ) DEFAULT NULL,
    `BLACKOUT` text,
    KEY `i1` ( `HOSTNAME` ( 25 ) ),
    KEY `i2` ( `PORT_NUMBER` )
) ENGINE = MyISAM DEFAULT CHARSET = latin1;


