-- This DDL was reverse engineered by
-- Toad for MySQL, Version 1.0.3
--
-- at:   JLT5160
-- from: localhost:patrol_report, an MySQL 4.1.8-nt-log database
--
-- on:   Mon Apr 11 11:33:57 2005
--
-- Generating CREATE statement for:
-- TABLE CONTENTS:pamdemo.changes

-- INSERT INTO pamdemo.changes (ID,RequestID,AgentID,variable,oldvalue,newvalue,date_modified)
--  VALUES (
